import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os

def send_email_with_attachment(receiver_email, 
                               file_path, 
                               sender_email="andmygreatesthonor@gmail.com",
                               sender_password="krcb meci rkyy labk", 
                            ):
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = receiver_email
        msg['Subject'] = "This is a question bank generated by Elijah" 

        file_name = os.path.basename(file_path)
        
        body = f"Questions from {file_name.replace('.csv', '.pdf')}"
        msg.attach(MIMEText(body, 'plain'))
        
        with open(file_path, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
        
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={file_path.split('/')[-1]}",
        )
        msg.attach(part)
        
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, receiver_email, msg.as_string())
            print("Email sent successfully.")

        os.remove(file_path)
    
    except Exception as e:
        print(f"Error: {e}")
